name: Ununtu 18.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    container:
      image: dimon4eg/ubuntu_nakama_base:u1804_b169_c3155
      volumes:
        - my_docker_volume:/volume_mount
    
    steps:
    - uses: actions/checkout@v1
    
    - name: build
      run: cd build/linux && ./build_linux.py
