name: Ununtu 18.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    container:
      image: dimon4eg/ubuntu_nakama_base:u1804_b169_c3155
      volumes:
        - my_docker_volume:/volume_mount
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    
    - name: build
      run: cd build/linux && ./build_linux.py

  nakama-server:
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
    - name: get docker-compose
      run: wget https://raw.githubusercontent.com/heroiclabs/nakama/master/docker-compose.yml

    - name: cur dir
      run: echo $PWD && ls

    - name: nakama-server
      run: docker-compose -f docker-compose.yml up -d

    - name: tests
      run: build/linux/build/Release_x64/test/nakama-test
