name: Ununtu 18.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    container:
      image: dimon4eg/ubuntu_nakama_base:u1804_b169_c3155
      volumes:
        - my_docker_volume:/volume_mount
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
#        fetch-depth: 1

    - name: cache third party
      id: cache_third_party
      uses: actions/cache@v1
      with:
        path: build/linux/build/Release_x64/third_party
        key: ${{ runner.os }}-third_party
    
    - name: build static
      run: cd build/linux && ./build_linux.py
    
    - name: upload static test binary
      uses: actions/upload-artifact@v1
      with:
        name: nakama-test
        path: build/linux/build/Release_x64/test/nakama-test

#    - name: build shared
#      run: cd build/linux && ./build_linux.py --so
    
#    - name: upload shared test binary
#      uses: actions/upload-artifact@v1
#      with:
#        name: nakama-test-so
#        path: build/linux/build/Release_x64/test/nakama-test

  nakama-server:
    runs-on: ubuntu-16.04
    needs: [build]

    steps:
    - name: download static test binary
      uses: actions/download-artifact@v1
      with:
        name: nakama-test

#    - name: download shared test binary
#      uses: actions/download-artifact@v1
#      with:
#        name: nakama-test-so

    - name: get docker-compose
      run: wget https://raw.githubusercontent.com/heroiclabs/nakama/master/docker-compose.yml

    - name: chmod static
      run: chmod u=rwx nakama-test/nakama-test

#    - name: chmod so
#      run: chmod u=rwx nakama-test-so/nakama-test

    - name: cur dir
      run: echo $PWD && cd nakama-test && ls -l

    - name: nakama-server
      run: docker-compose -f docker-compose.yml up -d

    - name: run tests (static)
      run: nakama-test/nakama-test

#    - name: run tests (shared)
#      run: nakama-test-so/nakama-test
